name: HydroTrack

options:
  bundleIdPrefix: com.kellyclaudeai
  deploymentTarget:
    iOS: "17.0"
  
settings:
  base:
    DEVELOPMENT_TEAM: 4PPGZNVG8G
    CODE_SIGN_STYLE: Automatic
    PRODUCT_BUNDLE_IDENTIFIER: com.kellyclaudeai.hydrotrack
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    SUPPORTS_MACCATALYST: false

targets:
  HydroTrack:
    type: application
    platform: iOS
    sources:
      - HydroTrack
    settings:
      base:
        INFOPLIST_FILE: HydroTrack/Info.plist
        PRODUCT_NAME: HydroTrack
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets: []
      gatherCoverageData: false

schemes:
  HydroTrack:
    build:
      targets:
        HydroTrack: all
    run:
      config: Debug
    archive:
      config: Release
